### PR TITLE
Spec 0.2.1

### PR DESCRIPTION
**Pull request by keighrim**

### CODE REVIEW

**Comment by keighrim** [comment]
now we need to think about how to *version* apps. I think git tags should be enough, and the version schema should be allowed to any reasonable ones.

**Comment by marcverhagen** [comment]
Yeah, some thought would be good. I am assuming that we use something like `tool-version` for the version of the tool wrapped. One question I had is we let the app version follow major-minor versions of the MMIF specifications or those of the SDK, or both. The later is a nightmare, and following either is somewhat arbitrary. I think any reasonable versioning scheme sounds fine, as long as the metadata give us the full story.

**Comment by keighrim** [comment]
Yeah, I guess we can require the app metadata to encode *target* MMIF version. One following issue, then, would be forcing agreement between MMIF version in metadata and `clams-python` (or `mmif-python`) version in `requirements.txt`.

**Comment by marcverhagen** [comment]
That issue has been keeping me up a little bit. We now have or will have versions for mmif-spec, mmif-python and clams-python and we really don't want to update an app each time we update one of those three. So that means we have to figure out when and how apps of different mmif/clams versions can work together.

By the way, I think this pull request is now somewhat obsolete.

**Comment by keighrim** [comment]
I moved the discussion to https://github.com/clamsproject/clams-apps/issues/14. As `spec-0.2.1` is merged to `develop`, I'll close this PR and open a new one from `develop` to `master`.

**Pull request closed without merging**
