### PR TITLE
adding uncased NER & dependency parser

### PR DESCRIPTION
**Pull request by JinnyViboonlarp**
options are added for app.py to
1. use a custom model, optimized for uncased text, for NER.
2. do dependency parsing.

### CODE REVIEW

**Comment by keighrim** [comment]
I'd like to suggest this PR be based on `dev` branch, not directly merged to the `main`.

**Comment by keighrim** [comment]
Is this PR still relevant at all? @marcverhagen do you still plan to review the code?

**Comment by JinnyViboonlarp** [comment]
I believe we’re not currently using information from the dependency parser,
but there might be a need to use uncased model on auto-detected transcripts
(though a default cased model is able to work reasonably well on uncased
transcripts).

**Comment by keighrim** [comment]
Closing this without merging.

**Pull request closed without merging**
